#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
  ifeq ($(GNUSTEP_MAKEFILES),)
    $(warning )
    $(warning Unable to obtain GNUSTEP_MAKEFILES setting from gnustep-config!)
    $(warning Perhaps gnustep-make is not properly installed,)
    $(warning so gnustep-config is not in your PATH.)
    $(warning )
    $(warning Your PATH is currently $(PATH))
    $(warning )
  endif
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = DSA-SpielHelfer
APP_NAME = DSA-SpielHelfer
DSA-SpielHelfer_APPLICATION_ICON = Logo-Fanprojekt.png
GNUSTEP_INSTALLATION_DOMAIN = USER


#
# Localization
#
DSA-SpielHelfer_LANGUAGES = German English
DSA-SpielHelfer_LOCALIZED_RESOURCE_FILES = \
DSA-SpielHelfer.gorm \
CharacterGeneration.gorm \
DSACharacter.gorm 


#
# Header files
#
DSA-SpielHelfer_HEADER_FILES = \
AppController.h \
AppDelegate.h \
DSADocumentController.h \
DSACharacterWindowController.h \
DSACharacterDocument.h \
DSACharacter.h \
CustomInitializer.h \
DSACharacterGenerationController.h \
Utils.h \
DSACharacterHero.h \
DSASpell.h \
DSAObject.h \
DSASpellResult.h \
DSATalent.h \
DSATrait.h \
DSAPositiveTrait.h \
DSANegativeTrait.h \
DSAFightingTalent.h \
DSAOtherTalent.h \
NSMutableDictionary+Extras.h \
NSFlippedView.h \
DSACharacterHeroHumanThorwaler.h \
DSACharacterHeroHuman.h \
DSACharacterViewModel.h \
DSACharacterHeroHumanRogue.h \
DSAProfession.h \
DSARightAlignedStringTransformer.h \
DSACharacterHeroHumanMage.h \
DSACharacterHeroElf.h \
DSACharacterHeroElfSnow.h \
DSACharacterHeroElfWood.h \
DSACharacterHeroElfMeadow.h \
DSACharacterHeroElfHalf.h \
DSACharacterHeroDwarf.h \
DSACharacterHeroDwarfAngroschPriest.h \
DSACharacterHeroDwarfGeode.h \
DSACharacterHeroDwarfFighter.h \
DSACharacterHeroDwarfCavalier.h \
DSACharacterHeroDwarfJourneyman.h \
DSACharacterHeroHumanJester.h \
DSACharacterHeroHumanAmazon.h \
DSACharacterHeroHumanHuntsman.h \
DSACharacterHeroHumanWarrior.h \
DSACharacterHeroHumanPhysician.h \
DSACharacterHeroHumanMoha.h \
DSACharacterHeroHumanNivese.h \
DSACharacterHeroHumanSeafarer.h \
DSACharacterHeroHumanMercenary.h \
DSACharacterHeroHumanSkald.h \
DSACharacterHeroHumanBard.h \
DSACharacterHeroHumanNovadi.h \
DSASpecialTalent.h \
DSACharacterHeroHumanNorbarde.h \
DSACharacterHeroHumanDruid.h \
DSACharacterHeroHumanJuggler.h \
DSACharacterHeroHumanCharlatan.h \
DSACharacterHeroHumanWitch.h \
DSACharacterPrintView.h \
DSAMapViewController.h \
DSAPannableScrollView.h \
DSAListSelectorPopoverViewController.h \
DSACharacterHeroHumanSharisad.h \
DSASpellWitchCurse.h \
DSASpellDruidRitual.h \
DSASpellMischievousPrank.h \
DSASpellGeodeRitual.h \
DSASpellElvenSong.h \
DSACharacterHeroHumanAlchemist.h \
DSACharacterHeroHumanShaman.h \
DSASpellShamanRitual.h \
DSACharacterHeroBlessed.h \
DSACharacterHeroBlessedPraios.h \
DSACharacterHeroBlessedRondra.h \
DSACharacterHeroBlessedEfferd.h \
DSACharacterHeroBlessedTravia.h \
DSACharacterHeroBlessedBoron.h \
DSACharacterHeroBlessedHesinde.h \
DSACharacterHeroBlessedFirun.h \
DSACharacterHeroBlessedTsa.h \
DSACharacterHeroBlessedPhex.h \
DSACharacterHeroBlessedPeraine.h \
DSACharacterHeroBlessedIngerimm.h \
DSACharacterHeroBlessedRahja.h \
DSACharacterHeroBlessedSwafnir.h \
DSALiturgy.h \
DSAEquipmentListViewController.h \
DSASlot.h \
DSAInventory.h \
DSABodyParts.h \
DSAEquipResult.h \
DSAInventorySlotView.h \
DSAInventoryManager.h \
DSAActionIcon.h \
DSAItemInspectionController.h \
DSAAventurianDate.h \
DSAAventurianCalendar.h \
DSASpellMageRitual.h \
DSATalentResult.h \
DSAAdventureWindowController.h \
DSAAdventure.h \
DSAAdventureDocument.h \
DSANameGenerator.h \
DSANameGenerationController.h \
DSARegenerationResult.h

#
# Objective-C Class files
#
DSA-SpielHelfer_OBJC_FILES = \
AppController.m \
AppDelegate.m \
DSADocumentController.m \
DSACharacterWindowController.m \
DSACharacterDocument.m \
DSACharacter.m \
CustomInitializer.m \
DSACharacterGenerationController.m \
Utils.m \
DSACharacterHero.m \
DSASpell.m \
DSAObject.m \
DSASpellResult.m \
DSATalent.m \
DSATrait.m \
DSAPositiveTrait.m \
DSANegativeTrait.m \
DSAFightingTalent.m \
DSAOtherTalent.m \
NSMutableDictionary+Extras.m \
NSFlippedView.m \
DSACharacterHeroHumanThorwaler.m \
DSACharacterHeroHuman.m \
DSACharacterViewModel.m \
DSACharacterHeroHumanRogue.m \
DSAProfession.m \
DSARightAlignedStringTransformer.m \
DSACharacterHeroHumanMage.m \
DSACharacterHeroElf.m \
DSACharacterHeroElfSnow.m \
DSACharacterHeroElfWood.m \
DSACharacterHeroElfMeadow.m \
DSACharacterHeroElfHalf.m \
DSACharacterHeroDwarf.m \
DSACharacterHeroDwarfAngroschPriest.m \
DSACharacterHeroDwarfGeode.m \
DSACharacterHeroDwarfFighter.m \
DSACharacterHeroDwarfCavalier.m \
DSACharacterHeroDwarfJourneyman.m \
DSACharacterHeroHumanAmazon.m \
DSACharacterHeroHumanJester.m \
DSACharacterHeroHumanHuntsman.m \
DSACharacterHeroHumanWarrior.m \
DSACharacterHeroHumanPhysician.m \
DSACharacterHeroHumanMoha.m \
DSACharacterHeroHumanNivese.m \
DSACharacterHeroHumanSeafarer.m \
DSACharacterHeroHumanMercenary.m \
DSACharacterHeroHumanSkald.m \
DSACharacterHeroHumanBard.m \
DSACharacterHeroHumanNovadi.m \
DSASpecialTalent.m \
DSACharacterHeroHumanNorbarde.m \
DSACharacterHeroHumanDruid.m \
DSACharacterHeroHumanJuggler.m \
DSACharacterHeroHumanCharlatan.m \
DSACharacterHeroHumanWitch.m \
DSACharacterPrintView.m \
DSAMapViewController.m \
DSAPannableScrollView.m \
DSAListSelectorPopoverViewController.m \
DSACharacterHeroHumanSharisad.m \
DSASpellWitchCurse.m \
DSASpellDruidRitual.m \
DSASpellMischievousPrank.m \
DSASpellGeodeRitual.m \
DSASpellElvenSong.m \
DSACharacterHeroHumanAlchemist.m \
DSACharacterHeroHumanShaman.m \
DSASpellShamanRitual.m \
DSACharacterHeroBlessed.m \
DSACharacterHeroBlessedPraios.m \
DSACharacterHeroBlessedRondra.m \
DSACharacterHeroBlessedEfferd.m \
DSACharacterHeroBlessedTravia.m \
DSACharacterHeroBlessedBoron.m \
DSACharacterHeroBlessedHesinde.m \
DSACharacterHeroBlessedFirun.m \
DSACharacterHeroBlessedTsa.m \
DSACharacterHeroBlessedPhex.m \
DSACharacterHeroBlessedPeraine.m \
DSACharacterHeroBlessedIngerimm.m \
DSACharacterHeroBlessedRahja.m \
DSACharacterHeroBlessedSwafnir.m \
DSALiturgy.m \
DSAEquipmentListViewController.m \
DSASlot.m \
DSAInventory.m \
DSABodyParts.m \
DSAEquipResult.m \
DSAInventorySlotView.m \
DSAInventoryManager.m \
DSAActionIcon.m \
DSAItemInspectionController.m \
DSAAventurianDate.m \
DSAAventurianCalendar.m \
DSASpellMageRitual.m \
DSATalentResult.m \
DSAAdventureWindowController.m \
DSAAdventure.m \
DSAAdventureDocument.m \
DSANameGenerator.m \
DSANameGenerationController.m \
DSARegenerationResult.m

#
# Other sources
#
DSA-SpielHelfer_OBJC_FILES += \
DSA-SpielHelfer_main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
