#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
  ifeq ($(GNUSTEP_MAKEFILES),)
    $(warning )
    $(warning Unable to obtain GNUSTEP_MAKEFILES setting from gnustep-config!)
    $(warning Perhaps gnustep-make is not properly installed,)
    $(warning so gnustep-config is not in your PATH.)
    $(warning )
    $(warning Your PATH is currently $(PATH))
    $(warning )
  endif
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = DSA-SpielHelfer
APP_NAME = DSA-SpielHelfer
DSA-SpielHelfer_APPLICATION_ICON = 
GNUSTEP_INSTALLATION_DOMAIN = USER


#
# Resource files
#
DSA-SpielHelfer_RESOURCE_FILES = \
Resources/Augenfarben.json \
Resources/Berufe.json \
Resources/Geburtstag.json \
Resources/Goetter.json \
Resources/Herkunft.json \
Resources/Talente.json \
Resources/Typus.json \
Resources/Magierakademien.json 


#
# Localization
#
DSA-SpielHelfer_LANGUAGES = German English
DSA-SpielHelfer_LOCALIZED_RESOURCE_FILES = \
DSA-SpielHelfer.gorm \
CharacterGeneration.gorm \
DSACharacter.gorm 


#
# Header files
#
DSA-SpielHelfer_HEADER_FILES = \
AppController.h \
AppDelegate.h \
DSADocumentController.h \
DSACharacterWindowController.h \
DSACharacterDocument.h \
DSACharacter.h \
CustomInitializer.h \
DSACharacterGenerationController.h \
Utils.h

#
# Objective-C Class files
#
DSA-SpielHelfer_OBJC_FILES = \
AppController.m \
AppDelegate.m \
DSADocumentController.m \
DSACharacterWindowController.m \
DSACharacterDocument.m \
DSACharacter.m \
CustomInitializer.m \
DSACharacterGenerationController.m \
Utils.m

#
# Other sources
#
DSA-SpielHelfer_OBJC_FILES += \
DSA-SpielHelfer_main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
