#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
  ifeq ($(GNUSTEP_MAKEFILES),)
    $(warning )
    $(warning Unable to obtain GNUSTEP_MAKEFILES setting from gnustep-config!)
    $(warning Perhaps gnustep-make is not properly installed,)
    $(warning so gnustep-config is not in your PATH.)
    $(warning )
    $(warning Your PATH is currently $(PATH))
    $(warning )
  endif
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = DSA-SpielHelfer
APP_NAME = DSA-SpielHelfer
DSA-SpielHelfer_APPLICATION_ICON = 
GNUSTEP_INSTALLATION_DOMAIN = USER


#
# Resource files
#
DSA-SpielHelfer_RESOURCE_FILES = \
Resources/DSACharacterLevelUp.gorm \
Resources/DSAAdventurePoints.gorm \
Resources/DSACharacterGenerationMagicalDabbler.gorm \
Resources/Character_1.png \
Resources/Character_10.png \
Resources/Character_100.png \
Resources/Character_101.png \
Resources/Character_102.png \
Resources/Character_103.png \
Resources/Character_104.png \
Resources/Character_105.png \
Resources/Character_106.png \
Resources/Character_11.png \
Resources/Character_12.png \
Resources/Character_13.png \
Resources/Character_14.png \
Resources/Character_15.png \
Resources/Character_16.png \
Resources/Character_17.png \
Resources/Character_18.png \
Resources/Character_19.png \
Resources/Character_2.png \
Resources/Character_20.png \
Resources/Character_21.png \
Resources/Character_22.png \
Resources/Character_23.png \
Resources/Character_24.png \
Resources/Character_25.png \
Resources/Character_26.png \
Resources/Character_27.png \
Resources/Character_28.png \
Resources/Character_29.png \
Resources/Character_3.png \
Resources/Character_30.png \
Resources/Character_31.png \
Resources/Character_32.png \
Resources/Character_33.png \
Resources/Character_34.png \
Resources/Character_35.png \
Resources/Character_36.png \
Resources/Character_37.png \
Resources/Character_38.png \
Resources/Character_39.png \
Resources/Character_4.png \
Resources/Character_40.png \
Resources/Character_41.png \
Resources/Character_42.png \
Resources/Character_43.png \
Resources/Character_44.png \
Resources/Character_45.png \
Resources/Character_46.png \
Resources/Character_47.png \
Resources/Character_48.png \
Resources/Character_49.png \
Resources/Character_5.png \
Resources/Character_50.png \
Resources/Character_51.png \
Resources/Character_52.png \
Resources/Character_53.png \
Resources/Character_54.png \
Resources/Character_55.png \
Resources/Character_56.png \
Resources/Character_57.png \
Resources/Character_58.png \
Resources/Character_59.png \
Resources/Character_6.png \
Resources/Character_60.png \
Resources/Character_61.png \
Resources/Character_62.png \
Resources/Character_63.png \
Resources/Character_64.png \
Resources/Character_65.png \
Resources/Character_66.png \
Resources/Character_67.png \
Resources/Character_68.png \
Resources/Character_69.png \
Resources/Character_7.png \
Resources/Character_70.png \
Resources/Character_71.png \
Resources/Character_72.png \
Resources/Character_73.png \
Resources/Character_74.png \
Resources/Character_75.png \
Resources/Character_76.png \
Resources/Character_77.png \
Resources/Character_78.png \
Resources/Character_79.png \
Resources/Character_8.png \
Resources/Character_80.png \
Resources/Character_81.png \
Resources/Character_82.png \
Resources/Character_83.png \
Resources/Character_84.png \
Resources/Character_85.png \
Resources/Character_86.png \
Resources/Character_87.png \
Resources/Character_88.png \
Resources/Character_89.png \
Resources/Character_9.png \
Resources/Character_90.png \
Resources/Character_91.png \
Resources/Character_92.png \
Resources/Character_93.png \
Resources/Character_94.png \
Resources/Character_95.png \
Resources/Character_96.png \
Resources/Character_97.png \
Resources/Character_98.png \
Resources/Character_99.png \
Resources/Augenfarben.json \
Resources/Berufe.json \
Resources/Geburtstag.json \
Resources/Goetter.json \
Resources/Herkunft.json \
Resources/Talente.json \
Resources/Typus.json \
Resources/Magierakademien.json \
Resources/Zauberfertigkeiten.json \
Resources/Magiedilettantenzauber.json \
Resources/Kriegerakademien.json 


#
# Localization
#
DSA-SpielHelfer_LANGUAGES = German English
DSA-SpielHelfer_LOCALIZED_RESOURCE_FILES = \
DSA-SpielHelfer.gorm \
CharacterGeneration.gorm \
DSACharacter.gorm 


#
# Header files
#
DSA-SpielHelfer_HEADER_FILES = \
AppController.h \
AppDelegate.h \
DSADocumentController.h \
DSACharacterWindowController.h \
DSACharacterDocument.h \
DSACharacter.h \
CustomInitializer.h \
DSACharacterGenerationController.h \
Utils.h \
DSACharacterHero.h \
DSASpell.h \
DSASpellObject.h \
DSASpellCreature.h \
DSAObject.h \
DSASpellResult.h \
DSATalent.h \
DSATrait.h \
DSAPositiveTrait.h \
DSANegativeTrait.h \
DSAFightingTalent.h \
DSAOtherTalent.h \
NSMutableDictionary+Extras.h \
NSFlippedView.h \
DSACharacterHeroHumanThorwaler.h \
DSACharacterHeroHuman.h \
DSACharacterViewModel.h \
DSACharacterHeroHumanRogue.h \
DSAProfession.h \
DSARightAlignedStringTransformer.h \
DSACharacterMagic.h \
DSACharacterHeroHumanMage.h \
DSACharacterHeroElf.h \
DSACharacterHeroElfSnow.h \
DSACharacterHeroElfWood.h \
DSACharacterHeroElfMeadow.h \
DSACharacterHeroElfHalf.h \
DSACharacterHeroDwarf.h \
DSACharacterHeroDwarfAngroschPriest.h \
DSACharacterHeroDwarfGeode.h \
DSACharacterHeroDwarfFighter.h \
DSACharacterHeroDwarfCavalier.h \
DSACharacterHeroDwarfJourneyman.h \
DSACharacterHeroHumanJester.h \
DSACharacterHeroHumanAmazon.h \
DSACharacterHeroHumanHuntsman.h \
DSACharacterHeroHumanWarrior.h \
DSACharacterHeroHumanPhysician.h \
DSACharacterHeroHumanMoha.h \
DSACharacterHeroHumanNivese.h \
DSACharacterHeroHumanSeafarer.h \
DSACharacterHeroHumanMercenary.h \
DSACharacterHeroHumanSkald.h \
DSACharacterHeroHumanBard.h \
DSACharacterHeroHumanNovadi.h \
DSASpecialTalent.h \
DSACharacterHeroHumanNorbarde.h \
DSACharacterHeroHumanDruid.h \
DSACharacterHeroHumanJuggler.h \
DSACharacterHeroHumanCharlatan.h \
DSACharacterHeroHumanWitch.h \
DSACharacterPrintView.h

#
# Objective-C Class files
#
DSA-SpielHelfer_OBJC_FILES = \
AppController.m \
AppDelegate.m \
DSADocumentController.m \
DSACharacterWindowController.m \
DSACharacterDocument.m \
DSACharacter.m \
CustomInitializer.m \
DSACharacterGenerationController.m \
Utils.m \
DSACharacterHero.m \
DSASpell.m \
DSAObject.m \
DSASpellResult.m \
DSATalent.m \
DSATrait.m \
DSAPositiveTrait.m \
DSANegativeTrait.m \
DSAFightingTalent.m \
DSAOtherTalent.m \
NSMutableDictionary+Extras.m \
NSFlippedView.m \
DSACharacterHeroHumanThorwaler.m \
DSACharacterHeroHuman.m \
DSACharacterViewModel.m \
DSACharacterHeroHumanRogue.m \
DSAProfession.m \
DSARightAlignedStringTransformer.m \
DSACharacterHeroHumanMage.m \
DSACharacterHeroElf.m \
DSACharacterHeroElfSnow.m \
DSACharacterHeroElfWood.m \
DSACharacterHeroElfMeadow.m \
DSACharacterHeroElfHalf.m \
DSACharacterHeroDwarf.m \
DSACharacterHeroDwarfAngroschPriest.m \
DSACharacterHeroDwarfGeode.m \
DSACharacterHeroDwarfFighter.m \
DSACharacterHeroDwarfCavalier.m \
DSACharacterHeroDwarfJourneyman.m \
DSACharacterHeroHumanAmazon.m \
DSACharacterHeroHumanJester.m \
DSACharacterHeroHumanHuntsman.m \
DSACharacterHeroHumanWarrior.m \
DSACharacterHeroHumanPhysician.m \
DSACharacterHeroHumanMoha.m \
DSACharacterHeroHumanNivese.m \
DSACharacterHeroHumanSeafarer.m \
DSACharacterHeroHumanMercenary.m \
DSACharacterHeroHumanSkald.m \
DSACharacterHeroHumanBard.m \
DSACharacterHeroHumanNovadi.m \
DSASpecialTalent.m \
DSACharacterHeroHumanNorbarde.m \
DSACharacterHeroHumanDruid.m \
DSACharacterHeroHumanJuggler.m \
DSACharacterHeroHumanCharlatan.m \
DSACharacterHeroHumanWitch.m \
DSACharacterPrintView.m

#
# Other sources
#
DSA-SpielHelfer_OBJC_FILES += \
DSA-SpielHelfer_main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
