#!/bin/sh

IMAGES=$(ls *webp)
SIZES="32x32 64x64 128x128 256x256 512x512"

for IMAGE in ${IMAGES}; do
        echo "$IMAGE"
        
        # Reset continue_outer_loop flag before checking
        unset continue_outer_loop
        
        for SIZE in ${SIZES}; do
                # Check if the image name contains the size pattern
                if echo "$IMAGE" | grep -q "${SIZE}"; then
                        continue_outer_loop="true"
                        break
                fi
        done
        
        # Check the flag to continue the outer loop
        if [ "X${continue_outer_loop}" = "Xtrue" ]; then
                unset continue_outer_loop
                continue
        fi
        
        BASENAME=$(basename "$IMAGE" .webp)
        
        for SIZE in ${SIZES}; do
                echo "convert $IMAGE -resize $SIZE ${BASENAME}-${SIZE}.webp"
                convert "$IMAGE" -resize "$SIZE" "${BASENAME}-${SIZE}.webp"
        done
done

